### ISSUE TITLE
Need an option so that a new line will start a new line, even if quotes are unclosed

### ISSUE THREAD

**Issue by dwalend** [tototoshi/scala-csv#18]
I've got some very dirty data, with quotes that aren't closed properly.

I'd like to be able to treat a new line in quotes as the same as a close quote, or have it report as an error. I don't see a way to configure that in scala-csv. Is there a way to do it?

If not, can you add it? It's not an uncommon problem.

Thanks,

Dave

**Comment by tototoshi** [comment]
Currently I have no plan to do it.
