### ISSUE TITLE
1.3.8 has not been tagged

### ISSUE THREAD

**Issue by tsuyoshizawa** [tototoshi/scala-csv#209]
Current latest version is 1.3.8.
However, I could not find a tagged version.

- https://github.com/tototoshi/scala-csv/releases/tag/1.3.7
- https://github.com/tototoshi/scala-csv/releases/tag/1.3.8

It would be helpful if you could add tags to make it easier to see the differences between versions.

**Comment by tototoshi** [comment]
Thanks! I pushed the tag.
https://github.com/tototoshi/scala-csv/releases/tag/1.3.8

**Comment by tsuyoshizawa** [comment]
Thank you!
