### ISSUE TITLE
Ignore malformed line

### ISSUE THREAD

**Issue by Zarko-Bojkovski** [tototoshi/scala-csv#211]
Hi I have some malformed lines in a CSV. 
Is there a way to just add an option to ignore the malformed lines?

**Comment by tototoshi** [comment]
Unfortunately, no.
CSV is a row-based format, but it also allows line breaks in the fields, so if you encounter an invalid line, you may not be able to determine where that line ends.

**Comment by Zarko-Bojkovski** [comment]
Thank you for the fast response!
