### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by xuwei-k** [tototoshi/scala-csv#313]
> UnsupportedClassVersionError: com/github/tototoshi/csv/LineReader has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

version 1.4.0

**Comment by tototoshi** [comment]
I forgot that this library still supports Java 8. I rebuilt it and published it as version 1.4.1.
