### ISSUE TITLE
Naming change suggestion

### ISSUE THREAD

**Issue by l15k4** [tototoshi/scala-csv#50]
Hey,

you have and abstraction over Csv (comma-separated-values) and Tsv (tab-separated-values) formats that are a subset of Dsv (delimiter-separated-values). 

https://en.wikipedia.org/wiki/Delimiter-separated_values

Wouldn't this be better ?
```scala
trait DSVFormat
trait CSVFormat extends DSVFormat
trait TSVFormat extends DSVFormat
```

Basically everything else too : `DSVParser, DSVReader, DSVWriter` ... All these components are working with DSVs no matter whether it is CSV, TSV or any other custom format.

Imho this would make `scala-csv` much more clean as to abstraction.  All these `CSV*` names are really ambiguous if you think about it.

**Comment by tototoshi** [comment]
I think CSV can mean character-separated values in this context.
