### ISSUE TITLE
Cannot use OutputStream after CSVWriter.close

### ISSUE THREAD

**Issue by chulkilee** [tototoshi/scala-csv#51]
If I pass System.out to CSVWriter and then call close on CSVWriter, System.out seems to be closed too. 

Closing own outputstream (e.g. when File or String is given) would make sense, but I'm not sure CSVWriter should close OutputStream directly passed into CSVWriter.

**Comment by tototoshi** [comment]
`close` releases all resources associated with the stream and underlying stream is also closed. this behavior is same as java.io.

if you don't want to close the stream, don't call `close`.
