### ISSUE TITLE
SBT can't resolve 1.3.0-SNAPSHOT version

### ISSUE THREAD

**Issue by danapsimer** [tototoshi/scala-csv#52]
SBT build fails when using the latest snapshot version.  I have the sonatype snapshots repo as a resolver and resolve other artifacts from it.  When I looked into the soanatype Snapshots repo, I did not find any version of scala-csv except 1.1.0-SNAPSHOT.

Please deploy the latest SNAPSHOT.

**Comment by harscoet** [comment]
+1

**Comment by tototoshi** [comment]
Deployed.
https://oss.sonatype.org/content/repositories/snapshots/com/github/tototoshi/scala-csv_2.11/1.3.0-SNAPSHOT/
