### ISSUE TITLE
Allowing values with commas

### ISSUE THREAD

**Issue by kentosi** [tototoshi/scala-csv#53]
CSV cell value that contains a comma are escaped with a double quote ["] when exported from Excel:
11, 22, "Something, Hello", bla.

This should parse as:
[11], [22], [Something, Hello], [bla]

Instead we get:
[11], [22], ["Something], [Hello"], [bla]

**Comment by tototoshi** [comment]
with scala-csv 1.2.2. I couldn't reproduce the issue.

```scala
import java.io.{ StringReader }
val sr = new StringReader("""11,22,"Something, Hello",bla.""")
val r = CSVReader.open(sr)
r.all.foreach(_.foreach(println))
```

output:
```
11
22
Something, Hello
bla.
```
