### ISSUE TITLE
Allow delimiters other than comma (,)

### ISSUE THREAD

**Issue by pedrorijo91** [tototoshi/scala-csv#54]
It would be nice to allow delimiters other than comma. In mac/Numbers if you open a CSV with comma (`,`)it does not parses correctly. With semi-collon (`;`) it does. 

`CSVWriter.writeRow` and `CSVWriter.writeAll` should receive the separator as an argument with default value the `format.delimiter.toString`as currently. The separator would be passed to `CSVWriter.writeNext` and everything would work by default as currently

**Comment by tototoshi** [comment]
Please see https://github.com/tototoshi/scala-csv#customizing-the-format
