### ISSUE TITLE
How about scala.collection.immutable.Stream[A] as the defacto source for the SourceLineReader.

### ISSUE THREAD

**Issue by hrlqn** [tototoshi/scala-csv#62]
@danapsimer 's refactoring is most welcome (https://github.com/tototoshi/scala-csv/commit/20b945e401ac5f61191e242e7032ff76bf575d07) and I was wondering if we could continue the refactoring and instead of dealing with scala.io.Source as the source of data we could strip it down all the way to scala.collection.immutable.Stream. 

In my mind at its core an ultimate source for a Scala lib CSVReader should be a [Scala/Java] collection (preferably lazy), besides Java Streams. This decouples the parser from the actual technology of delivering those bytes to the CSVReader.

If a client deals with a scala.io.Source it is fairly straightforward to convert into a Stream or an Iterator into a Stream.

My use-case for instance is:
I have to parse a lot of CSV files which sit in Zip files. Instead of unzipping the file, read its content from disc and then delete the uncompressed file, I am reading the zip file directly using ZipInputStream which I apply a codec to on the fly and provide the data as a scala.collection.immutable.Stream.

I will be happy to help if need be.

**Comment by tototoshi** [comment]
I want some example code that describes your use-case.

I think Source is more useful because before converting a file to Stream[A], we use Source or Reader.

```scala
Source.fromFile(file).getLines.toStream
```

And Stream[A] can consume a lot of memory when the input files are very large. Source or Reader are designed to handle them and more reasonable in this library.

**Comment by hrlqn** [comment]
@tototoshi Thank you for your reply. I should have done a better job explaining my problem.

My concrete example is: my team receives some AWS S3 endpoints from where we need to pick up fairly large zip files (10-20GB) containing one or more CSV files within each zip file. 

The time constraints from receiving a notification (that the files are available) to having them all parsed are quite aggressive. There is absolutely no reason for us to step out of the JVM and uncompress these files (using unzip for instance), then convert to proper encoding and then read them as files via the CSVReader. This involves too many steps making it both error prone as well as not the best approach performance/resources wise (uncompress: is a read-write, encoding another read-write and then CSVReader is another read). 

In such case going against the zip files directly (using ZipInputStream) and applying the correct character encoding after which this stream could be fed directly into CSVReader makes for a nice streamlined pipeline.

In an ideal scenario very large amounts of data come as streams which are then transformed, joined, split, reduced (and other available Stream operations) ... over pipelines.

In order to put all things together I ended up with something similar to:
http://stackoverflow.com/questions/4070446/how-to-read-zipinputstream-into-chararrayreader
and was wondering if there is a leaner way to do this.

In regards of 
```And Stream[A] can consume a lot of memory when the input files are very large. Source or Reader are designed to handle them and more reasonable in this library``` 
do you speak from personal experience?

**Comment by danapsimer** [comment]
@hrlqn I am doing almost exactly this and that was the main reason for my pull request adding support for `scala.io.Source` as an input to CSVReader.  This function is used to create a source from a zip file entry:

```scala
private def zipEntrySource(entryName: String, zipFileSource: URL, encoding: String = "UTF-8"): Source = {
  val zipIS = new ZipInputStream(zipFileSource.openStream())
  while (true) {
    zipIS.getNextEntry match {
      case z: ZipEntry =>
        if (z.getName.equals(entryName)) {
          return Source.fromInputStream(zipIS, encoding)
        }
      case _ =>
        throw new FileNotFoundException(s"$entryName not found in $zipFileSource")
    }
  }
  throw new FileNotFoundException(s"$entryName not found in $zipFileSource")
}
```

the zipFileSource is a URL that points at an HTTP server.  The entire process, works as the zip file is streamed from the HTTP server.

**Comment by hrlqn** [comment]
@danapsimer This is perfect. I wonder how did I miss the scala.io.Source.fromInputStream factory method?!

@tototoshi My apologies, I am closing this ticket.
