### ISSUE TITLE
Publish non-snapshot for 1.3.0

### ISSUE THREAD

**Issue by matanster** [tototoshi/scala-csv#63]
There's an sbt bug epic about snapshot dependencies - https://github.com/sbt/sbt/issues/1780. As 1.3.0 seems pretty stable for a while, would it be possible to publish a non-snapshot version?

This is really plaguing some builds and a non snapshot will be very much appreciated.

Some of the subordinate sbt bugs mean that the snapshot dependency may be downloaded several times per project, and even without that, snapshots get resolved on every `update` which is quite needless in this case. Other listed bugs simply crash builds that have a snapshot dependency.

If it helps with anything, a non-snapshot release can use a different number, keeping 1.3.0 evergreen, if being ever-green is a desire here.

**Comment by justjoheinz** [comment]
+1

**Comment by teroxik** [comment]
+1

**Comment by tototoshi** [comment]
Thank you all.
Just published 1.3.0 to sonatype repository.
It will be cloned to maven central in a few hours.
