### ISSUE TITLE
Last field is ignored if it is empty.

### ISSUE THREAD

**Issue by gelisam** [tototoshi/scala-csv#66]
```
scala> CSVParser.parse("a,b,c,\"\",d,\"\"", '\\', ',', '"')
res0: Option[List[String]] = Some(List(a, b, c, , d))
```

Interestingly, the last field is only missing if it is surrounded in quotes:

```
scala> CSVParser.parse("a,b,c,\"\",d,", '\\', ',', '"')
res1: Option[List[String]] = Some(List(a, b, c, , d, ))
```

**Comment by gelisam** [comment]
I found a workaround: if the line ends with a newline then it works.

    scala> CSVParser.parse("a,b,c,\"\",d,\"\"\n", '\\', ',', '"')
    res2: Option[List[String]] = Some(List(a, b, c, , d, ))

**Comment by hyperdash** [comment]
+1

**Comment by dieresys** [comment]
But it doesn't work on single fields:
scala> CSVParser.parse("\"\"\n", '\\', ',', '"')
res13: Option[List[String]] = Some(List())
