### ISSUE TITLE
com.github.tototoshi.csv.MalformedCSVException: <U+FEFF>

### ISSUE THREAD

**Issue by git4sun** [tototoshi/scala-csv#74]
I was trying to parse two csv files both started with \<U+FEFF\> . one is fine, the other throws the malformed exception. Here's the error:

scala> res0.parseLine("""\<U+FEFF\>"Post ID",Permalink,"Post Message",Type""")
com.github.tototoshi.csv.MalformedCSVException \<U+FEFF\>"Post ID",Permalink,"Post Message",Type
  at com.github.tototoshi.csv.CSVParser$.parse(CSVParser.scala:139)
  at com.github.tototoshi.csv.CSVParser.parseLine(CSVParser.scala:301)
  ... 43 elided

scala> res0.parseLine(""""Post ID",Permalink,"Post Message",Type""")
res2: Option[List[String]] = Some(List(Post ID, Permalink, Post Message, Type))

scala> res0.parseLine("""\<U+FEFF\>Date,"Lifetime Total Likes","Daily New Likes"""")
res3: Option[List[String]] = Some(List(\<U+FEFF\>Date, Lifetime Total Likes, Daily New Likes))

It looks like \<U+FEFF\> followed by " will trigger the exception. How do I resolve this?

**Comment by tototoshi** [comment]
Thanks for reporting.
Fixed by 1edc03433b4961642c1d761cb457447f35179ca4
