### ISSUE TITLE
Unable to read tsv file containing ¥ character

### ISSUE THREAD

**Issue by doyaaaaaken** [tototoshi/scala-csv#81]
When I read tsv file by using allWithOrderedHeaders() method of CSVReader class,
it throws com.github.tototoshi.csv.MalformedCSVException.

The file contains '¥' character, and after I delete that character, there comes no errors.
The file is shift-jis.

**Comment by tototoshi** [comment]
`com.github.tototoshi.csv.TSVFormat` treats backslash as escape character.
This behavior can be changed by defining custom format, like:

```scala
val tsvFormat = new TSVFormat {
  override val escapeChar = '#' // use '#' as escape character instead of backslash
}
val reader = CSVReader.open("src/main/resources/test.csv")(tsvFormat)
```

If you are not using any character for escaping, you don't need to use scala-csv. `String#split` might be enough.

**Comment by doyaaaaaken** [comment]
Thank you for your kind advice!!
I tried your way, and successfully worked!
