### ISSUE TITLE
Unable to parse quoted text 

### ISSUE THREAD

**Issue by anonanton** [tototoshi/scala-csv#95]
Breaks on cases like 

791105,995371,8800,8800,8800, 36 months,5.42,265.41,A,A1,Home Depot,9 years,MORTGAGE,43000,Verified,20110601T000000,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail.action?loan_id=791105,,debt_consolidation,""Get Out of Debt"",355xx,AL,2.57,0,19880101T000000,0,,,9,0,4154,6.6,21,f,0,0,9355.69,9355.69,8800,555.69,0,0,0,20130101T000000,4852.65,,20150201T000000,0,,1,0,Fully Paid,1,0,10,6,0.2,1,1,1,0,7.40679,20140601T000000,1,1,1

the ,""Get Out of Debt"", part

and

801516,1007103,3200,3200,3200, 36 months,11.49,105.51,B,B4,,n/a,RENT,12000,Verified,20110701T000000,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail.action?loan_id=801516,"  Borrower added on 06/29/11 > I have been dreaming of starting my own business for awhile now, and you can make this dream come true. <br/><br/>I have been restoring my credit for the last couple of years which i feel should give you confidence and peace of mind knowing that I am responsible and dedicated to repay this loan.<br/>",small_business,""For those that said i couldn't"",864xx,AZ,5.8,0,20050301T000000,2,,,4,0,1711,38.9,11,f,0,0,3580.46,3580.46,3200,380.46,0,0,0,20121001T000000,2054.22,,20140301T000000,0,,1,0,Fully Paid,1,0,0,5,0.8,1,1,1,1,10.551,20140701T000000,1,1,1

the ,""For those that said i couldn't"", part

**Comment by axb21** [comment]
Can confirm this. Also breaks when the quote character is escaped, e.g.

0,1,"this is \"quoted\" text",124312

**Comment by tototoshi** [comment]
`"` is escaped with double quote by default. If you want to escape with backslash, override this behavior like this.

```scala
scala> val s= """0,1,"this is \"quoted\" text",124312"""
s: String = 0,1,"this is \"quoted\" text",124312

scala> val format = new DefaultCSVFormat {
     |   override val escapeChar: Char = '\\'
     | }
format: com.github.tototoshi.csv.DefaultCSVFormat = $anon$1@5d9df3c2

scala> val result = CSVReader.open(io.Source.fromString(s))(format).all
result: List[List[String]] = List(List(0, 1, this is "quoted" text, 124312))
```

**Comment by axb21** [comment]
How about when reading from a file?
